// Generated by CoffeeScript 1.7.1
"use strict";

/*
Base class for adapters
@type rest.adapter.Base
@param {Object} model service to query the database
@param {string} name  name of the model
 */
var Base;

Base = (function() {
  function Base(_model, _name) {
    this._model = _model;
    this._name = _name != null ? _name : "model";
  }

  Base.prototype.getModel = function() {
    return this._model;
  };

  Base.prototype.setModel = function(_model) {
    this._model = _model;
  };

  Base.prototype.getName = function() {
    return this._name;
  };

  Base.prototype.setName = function(_name) {
    this._name = _name;
  };


  /*
  findAll resources
  @param  {Object}   params   
  @param  {Function} callback
   */

  Base.prototype.findAll = function(params, callback) {};


  /*
  find resource
  @param  {String|Number}   id       
  @param  {Function} callback
   */

  Base.prototype.find = function(id, callback) {};


  /*
  create resource
  @param  {Object}   raw     
  @param  {Function} callback
   */

  Base.prototype.create = function(raw, callback) {};


  /*
  update resource
  @param  {String|Number}   id       
  @param  {Object}   raw      
  @param  {Function} callback
   */

  Base.prototype.update = function(id, raw, callback) {};


  /*
  delete resource
     	@param  {String|Number}   id       
     	@param  {Function} callback
   */

  Base.prototype["delete"] = function(id, callback) {};

  return Base;

})();

module.exports = Base;

//# sourceMappingURL=Base.map
