// Generated by CoffeeScript 1.6.3
var AdapterNameResolver, Base, MongooseAdapter;

MongooseAdapter = require('./adapter/MongooseAdapter');

Base = require('./adapter/Base');

/*
Object that loads an adapter according to a string.
*/


AdapterNameResolver = (function() {
  function AdapterNameResolver() {}

  AdapterNameResolver.prototype.resolve = function(name) {
    if (name instanceof Base) {
      return name;
    }
    switch (name) {
      case 'mongoose':
        return new MongooseAdapter();
    }
  };

  return AdapterNameResolver;

})();

module.exports = AdapterNameResolver;

/*
//@ sourceMappingURL=AdpaterNameResolver.map
*/
