// Generated by CoffeeScript 1.7.1
"use strict";

/*
@type rest.errors.ModelNotFoundError
 */
var ModelNotFoundError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ModelNotFoundError = (function(_super) {
  __extends(ModelNotFoundError, _super);


  /*
  	@param {String} message
   */

  function ModelNotFoundError(message) {
    this.message = message != null ? message : "error";
    ModelNotFoundError.__super__.constructor.apply(this, arguments);
    this.name = "ModelNotFoundError";
    this.type = "ModelNotFoundError";
  }

  return ModelNotFoundError;

})(Error);

module.exports = ModelNotFoundError;


/* end */

//# sourceMappingURL=ModelNotFoundError.map
